Repository 5G-MAG/rt-5gms-application-server, pull requests merged in 2022-10, with the labels that each got.

#29 Update docs and configuration to add provisioning-session-id UUID.
  docs/README.md
  docs/example-application-server.conf
  src/rt_5gms_as/context.py
  src/rt_5gms_as/proxies/nginx-server.conf.tmpl
  src/rt_5gms_as/proxies/nginx.py
Labels: documentation, enhancement

#32 Add lifecycle management for web proxy daemon
  src/rt_5gms_as/app.py
  src/rt_5gms_as/context.py
  src/rt_5gms_as/proxies/nginx.py
  src/rt_5gms_as/proxy_factory.py
Labels: enhancement

#36 Add ATTIBUTION_NOTICE and update README
  ATTRIBUTION_NOTICE
  README.md
Labels: documentation

#38 Add a hint to the documentation to checkout the correct branch for fe…
  README.md
Labels: documentation
